#!/usr/bin/env bash

# BSPWM MONITORS
bspc monitor -d I II III IV V VI VII VIII

# OTHER STAFF
sxhkd &
nitrogen --set-zoom-fill --random ~/.wallpapers/ --save &
$HOME/.config/polybar/launch.sh &
picom -b &
xsetroot -cursor_name left_ptr &
bgchd -dir /home/ash1vt/.wallpapers -intv 1m -bcknd ntrgn -rpl &
cbatticon -u 20 -i standard -l 10 -r 5 &

# BORDER AND GAPS
bspc config border_width         2
bspc config window_gap          10

# COLORS
bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#d8dee9"

# SPACE COLOR WHEN CHOOSING LOCATION OF NEW WINDOW
bspc config presel_feedback_color "fd2e59"

# SPLIT RATIO
bspc config split_ratio          0.5

# FOCUS ON WINDOW WHEN HOVER
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

# MONOCLE CONFIG
bspc config single_monocle	     false
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

# DIFFERENT APPS RULES
bspc rule -a Firefox state=floating rectangle=1350x900+50+90 desktop='^1'
#bspc rule -a TelegramDesktop state=floating follow=off desktop='^1'
bspc rule -a TelegramDesktop state=floating follow=off rectangle=420x900+1450+90 desktop='^1'
bspc rule -a Lutris state=floating follow=off rectangle=1200x700+360+190 desktop='^6' 
bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
bspc rule -a Media viewer rectangle=1350x900+285+90 state=floating
bspc rule -a Inkscape desktop='^3'
bspc rule -a Blender desktop='^2'
